### PR TITLE
plugins/bridge: clean masquerading rules

### PR DESCRIPTION
**Pull request by iaguis**
In the Add command we set up masquerading rules that didn't have a
corresponding clean-up code in Del.

Add the clean-up code.

### CODE REVIEW

**Comment by dcbw** [comment]
LGTM

**Comment by yifan-gu** [comment]
cc @steveeJ @euank

**Comment by squaremo** [comment]
(NB in the absence of tests here, I went through the set-up described in the rkt bug mentioned above using cnitool, and confirmed that the iptables-save output showed that rules were removed when the network was deleted).

**Comment by steveeJ** [comment]
Thanks @iaguis!

**Pull request merged**
