### PR TITLE
Fix loopback result

### LINKED ISSUE #141: plugins/loopback: unmarshalling error when added with cnitool
Placing the configuration `/etc/cni/net.d/00-lo.conf`:
```
{
    "name": "lo",
    "type": "loopback"
}
```

The attempt to add it with `cnitool` fails like so:
```
 bin/ # CNI_PATH=`pwd` ./cnitool add lo /proc/self/ns/net
add: unexpected end of JSON input
```
While *lo* is up the error is valid. The plugin doesn't return a valid result.

This should also be covered in a test.

/cc @zachgersh

### PR DESCRIPTION
**Pull request by steveeJ**
Fixes #141.

---
- [x] Fix result
- [x] Add testcase

### CODE REVIEW

**Comment by jonboulle** [comment]
pluings -> plugins in https://github.com/steveeJ/cni/commit/539b04fd3e538da9bc4d78f628676be0983a54bd commit message

**Comment by steveeJ** [comment]
Thanks @jonboulle :-) Fixed and testcase added.

**Comment by zachgersh** [comment]
@steveeJ - this is great!

Could we actually add a test case for del though? I could totally help with this as needed.

**Comment by steveeJ** [comment]
@zachgersh sure! I added the testcase.

**Comment by zachgersh** [comment]
@steveeJ Awesome! LGTM - once the tests pass ;)

**Pull request merged**
