### PR TITLE
build script: remove the _workspace from GOPATH

### PR DESCRIPTION
**Pull request by zachgersh**
Missed this when finishing out #156

### CODE REVIEW

**Comment by jonboulle** [comment]
I know I'm just a lowly non-maintainer these days, but could you please follow the [commit message guidelines](https://github.com/appc/cni/blob/master/CONTRIBUTING.md#format-of-the-commit-message)? :-)

**Comment by zachgersh** [comment]
@jonboulle thanks for point that out - fixed.

**Comment by iaguis** [comment]
it's still missing the `<subsystem>: ` part :S

**Comment by steveeJ** [comment]
Almost! For readability we use commit headlines in style of `<subsystem>: <what changed>`, i.e. `build script: don't append _workspace to GOPATH`

**Comment by zachgersh** [comment]
Thanks @steveeJ / @iaguis - leveling up my PR messages

**Comment by steveeJ** [comment]
Great, thanks!

**Pull request merged**
