### PR TITLE
pkg/skel: add rudimentary unit tests

### PR DESCRIPTION
**Pull request by steveeJ**
This is an attempt to testing the PluginMain() function of the skel pkg.
We should be able to do better by using a mockable interface for the
plugins, but this is a start.

### CODE REVIEW

**Comment by zachgersh** [comment]
hey @steveeJ - this was actually the package I was going to work on testing :D Would you mind if I actually put some tests in for this so you can review?

**Comment by steveeJ** [comment]
Sure! Are you going to base them on top of this? If not, please let me know why for education purposes.

**Comment by zachgersh** [comment]
I was totally going to base it off of what you had already started.

**Comment by steveeJ** [comment]
Sounds good. Let's not make it more complicated than it has to be andjust merge this, then continue delivering PRs against master. 

@zachgersh agreed?

**Comment by zachgersh** [comment]
Great idea!

**Comment by steveeJ** [comment]
Okay, for the sake of practicing the procedure, you may now remove the "needs review" label and add the "reviewed/lgtm" label and I will then merge :-)

**Pull request merged**
