### PR TITLE
added the String method to Result type

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <aanm90@gmail.com>

### CODE REVIEW

**Comment by steveeJ** [comment]
Please give a brief explanation when this can be useful, a simple use-case would be enough.

**Comment by aanm** [comment]
Logging/debugging, the `prettyString` method is huge (with those spaces) to print in a log file/output.

**Comment by steveeJ** [comment]
SGTM! Please add that explanation as a docstring above the method and it's good to go.

**Comment by aanm** [comment]
Done!

**Comment by steveeJ** [comment]
Thanks @aanm!

**Pull request merged**
